[build]
  publish = ".next"
  command = "npm run build"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-api-key"
  function = "get-api-key"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-firebase-config"
  function = "get-firebase-config"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-openai-api-key"
  function = "get-openai-api-key"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-firebase-api-key"
  function = "get-firebase-api-key"
