[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

# Functions configuration
[[functions]]
  path = "/.netlify/functions/allowed-tickers"
  function = "allowed-tickers"

[[functions]]
  path = "/.netlify/functions/get-ai-rating"
  function = "get-ai-rating"

[[functions]]
  path = "/.netlify/functions/get-gemini-ai-rating"
  function = "get-gemini-ai-rating"

[[functions]]
  path = "/.netlify/functions/getNews"
  function = "getNews"

# Edge Functions
[[edge_functions]]
  path = "/.netlify/edge-functions/get-api-key"
  function = "get-api-key"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-firebase-config"
  function = "get-firebase-config"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-openai-api-key"
  function = "get-openai-api-key"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-firebase-api-key"
  function = "get-firebase-api-key"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-firebase-auth-domain"
  function = "get-firebase-auth-domain"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-firebase-storage-bucket"
  function = "get-firebase-storage-bucket"

# Redirect rules (optional)
[[redirects]]
  from = "/allowed-tickers"
  to = "/.netlify/functions/allowed-tickers"
  status = 200
