[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions" # Correctly defines the functions directory
  edge_functions = "netlify/edge-functions"

# Edge Functions
[[edge_functions]]
  path = "/.netlify/edge-functions/get-api-key"
  function = "get-api-key"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-firebase-config"
  function = "get-firebase-config"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-openai-api-key"
  function = "get-openai-api-key"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-firebase-api-key"
  function = "get-firebase-api-key"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-firebase-auth-domain"
  function = "get-firebase-auth-domain"

[[edge_functions]]
  path = "/.netlify/edge-functions/get-firebase-storage-bucket"
  function = "get-firebase-storage-bucket"
